#############################################################################
# Makefile for building: Project2017
# Generated by qmake (2.01a) (Qt 4.8.6) on: lun lug 10 22:07:08 2017
# Project:  Project2017.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Project2017.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Account.cpp \
		Admin.cpp \
		AdminController.cpp \
		AdminWidget.cpp \
		Book.cpp \
		Controller.cpp \
		Data.cpp \
		InsertBookWidget.cpp \
		InsertUserWidget.cpp \
		Item.cpp \
		Librarian.cpp \
		LibrarianController.cpp \
		LibrarianWidget.cpp \
		LoginController.cpp \
		LoginWidget.cpp \
		Magazine.cpp \
		main.cpp \
		MainWindow.cpp \
		MyBookWidget.cpp \
		UpdateUserWidget.cpp \
		User.cpp \
		UserBookViewWidget.cpp \
		UserController.cpp \
		UserWidget.cpp \
		ViewBookWidget.cpp \
		ViewUserWidget.cpp moc_AdminWidget.cpp \
		moc_InsertBookWidget.cpp \
		moc_InsertUserWidget.cpp \
		moc_LibrarianWidget.cpp \
		moc_LoginWidget.cpp \
		moc_MainWindow.cpp \
		moc_MyBookWidget.cpp \
		moc_UpdateUserWidget.cpp \
		moc_UserBookViewWidget.cpp \
		moc_UserWidget.cpp \
		moc_ViewBookWidget.cpp \
		moc_ViewUserWidget.cpp
OBJECTS       = Account.o \
		Admin.o \
		AdminController.o \
		AdminWidget.o \
		Book.o \
		Controller.o \
		Data.o \
		InsertBookWidget.o \
		InsertUserWidget.o \
		Item.o \
		Librarian.o \
		LibrarianController.o \
		LibrarianWidget.o \
		LoginController.o \
		LoginWidget.o \
		Magazine.o \
		main.o \
		MainWindow.o \
		MyBookWidget.o \
		UpdateUserWidget.o \
		User.o \
		UserBookViewWidget.o \
		UserController.o \
		UserWidget.o \
		ViewBookWidget.o \
		ViewUserWidget.o \
		moc_AdminWidget.o \
		moc_InsertBookWidget.o \
		moc_InsertUserWidget.o \
		moc_LibrarianWidget.o \
		moc_LoginWidget.o \
		moc_MainWindow.o \
		moc_MyBookWidget.o \
		moc_UpdateUserWidget.o \
		moc_UserBookViewWidget.o \
		moc_UserWidget.o \
		moc_ViewBookWidget.o \
		moc_ViewUserWidget.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Project2017.pro
QMAKE_TARGET  = Project2017
DESTDIR       = 
TARGET        = Project2017

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project2017.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Project2017.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Project2017.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Project20171.0.0 || $(MKDIR) .tmp/Project20171.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Project20171.0.0/ && $(COPY_FILE) --parents Account.h Admin.h AdminController.h AdminWidget.h Book.h Controller.h Data.h InsertBookWidget.h InsertUserWidget.h Item.h Librarian.h LibrarianController.h LibrarianWidget.h LoginController.h LoginWidget.h Magazine.h MainWindow.h MyBookWidget.h UpdateUserWidget.h User.h UserBookViewWidget.h UserController.h UserWidget.h ViewBookWidget.h ViewUserWidget.h .tmp/Project20171.0.0/ && $(COPY_FILE) --parents Account.cpp Admin.cpp AdminController.cpp AdminWidget.cpp Book.cpp Controller.cpp Data.cpp InsertBookWidget.cpp InsertUserWidget.cpp Item.cpp Librarian.cpp LibrarianController.cpp LibrarianWidget.cpp LoginController.cpp LoginWidget.cpp Magazine.cpp main.cpp MainWindow.cpp MyBookWidget.cpp UpdateUserWidget.cpp User.cpp UserBookViewWidget.cpp UserController.cpp UserWidget.cpp ViewBookWidget.cpp ViewUserWidget.cpp .tmp/Project20171.0.0/ && (cd `dirname .tmp/Project20171.0.0` && $(TAR) Project20171.0.0.tar Project20171.0.0 && $(COMPRESS) Project20171.0.0.tar) && $(MOVE) `dirname .tmp/Project20171.0.0`/Project20171.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Project20171.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_AdminWidget.cpp moc_InsertBookWidget.cpp moc_InsertUserWidget.cpp moc_LibrarianWidget.cpp moc_LoginWidget.cpp moc_MainWindow.cpp moc_MyBookWidget.cpp moc_UpdateUserWidget.cpp moc_UserBookViewWidget.cpp moc_UserWidget.cpp moc_ViewBookWidget.cpp moc_ViewUserWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AdminWidget.cpp moc_InsertBookWidget.cpp moc_InsertUserWidget.cpp moc_LibrarianWidget.cpp moc_LoginWidget.cpp moc_MainWindow.cpp moc_MyBookWidget.cpp moc_UpdateUserWidget.cpp moc_UserBookViewWidget.cpp moc_UserWidget.cpp moc_ViewBookWidget.cpp moc_ViewUserWidget.cpp
moc_AdminWidget.cpp: InsertUserWidget.h \
		AdminController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		ViewUserWidget.h \
		UpdateUserWidget.h \
		AdminWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) AdminWidget.h -o moc_AdminWidget.cpp

moc_InsertBookWidget.cpp: LibrarianController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		InsertBookWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) InsertBookWidget.h -o moc_InsertBookWidget.cpp

moc_InsertUserWidget.cpp: AdminController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		InsertUserWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) InsertUserWidget.h -o moc_InsertUserWidget.cpp

moc_LibrarianWidget.cpp: InsertBookWidget.h \
		LibrarianController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		ViewBookWidget.h \
		UpdateUserWidget.h \
		LibrarianWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) LibrarianWidget.h -o moc_LibrarianWidget.cpp

moc_LoginWidget.cpp: LoginController.h \
		Data.h \
		Account.h \
		Item.h \
		LoginWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) LoginWidget.h -o moc_LoginWidget.cpp

moc_MainWindow.cpp: LoginWidget.h \
		LoginController.h \
		Data.h \
		Account.h \
		Item.h \
		AdminWidget.h \
		InsertUserWidget.h \
		AdminController.h \
		Controller.h \
		ViewUserWidget.h \
		UpdateUserWidget.h \
		LibrarianWidget.h \
		InsertBookWidget.h \
		LibrarianController.h \
		ViewBookWidget.h \
		UserWidget.h \
		MyBookWidget.h \
		UserController.h \
		UserBookViewWidget.h \
		MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_MyBookWidget.cpp: UserController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		MyBookWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MyBookWidget.h -o moc_MyBookWidget.cpp

moc_UpdateUserWidget.cpp: Controller.h \
		Account.h \
		UpdateUserWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UpdateUserWidget.h -o moc_UpdateUserWidget.cpp

moc_UserBookViewWidget.cpp: UserController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		UserBookViewWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UserBookViewWidget.h -o moc_UserBookViewWidget.cpp

moc_UserWidget.cpp: MyBookWidget.h \
		UserController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		UserBookViewWidget.h \
		UpdateUserWidget.h \
		UserWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) UserWidget.h -o moc_UserWidget.cpp

moc_ViewBookWidget.cpp: LibrarianController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		ViewBookWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ViewBookWidget.h -o moc_ViewBookWidget.cpp

moc_ViewUserWidget.cpp: AdminController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		ViewUserWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ViewUserWidget.h -o moc_ViewUserWidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Account.o: Account.cpp Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Account.o Account.cpp

Admin.o: Admin.cpp Admin.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Admin.o Admin.cpp

AdminController.o: AdminController.cpp AdminController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		Admin.h \
		Librarian.h \
		User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AdminController.o AdminController.cpp

AdminWidget.o: AdminWidget.cpp AdminWidget.h \
		InsertUserWidget.h \
		AdminController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		ViewUserWidget.h \
		UpdateUserWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AdminWidget.o AdminWidget.cpp

Book.o: Book.cpp Book.h \
		Item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Book.o Book.cpp

Controller.o: Controller.cpp Controller.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o Controller.cpp

Data.o: Data.cpp Data.h \
		Account.h \
		Item.h \
		Admin.h \
		Librarian.h \
		User.h \
		Book.h \
		Magazine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Data.o Data.cpp

InsertBookWidget.o: InsertBookWidget.cpp InsertBookWidget.h \
		LibrarianController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InsertBookWidget.o InsertBookWidget.cpp

InsertUserWidget.o: InsertUserWidget.cpp InsertUserWidget.h \
		AdminController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InsertUserWidget.o InsertUserWidget.cpp

Item.o: Item.cpp Item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Item.o Item.cpp

Librarian.o: Librarian.cpp Librarian.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Librarian.o Librarian.cpp

LibrarianController.o: LibrarianController.cpp LibrarianController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		Book.h \
		Magazine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LibrarianController.o LibrarianController.cpp

LibrarianWidget.o: LibrarianWidget.cpp LibrarianWidget.h \
		InsertBookWidget.h \
		LibrarianController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		ViewBookWidget.h \
		UpdateUserWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LibrarianWidget.o LibrarianWidget.cpp

LoginController.o: LoginController.cpp LoginController.h \
		Data.h \
		Account.h \
		Item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginController.o LoginController.cpp

LoginWidget.o: LoginWidget.cpp LoginWidget.h \
		LoginController.h \
		Data.h \
		Account.h \
		Item.h \
		MainWindow.h \
		AdminWidget.h \
		InsertUserWidget.h \
		AdminController.h \
		Controller.h \
		ViewUserWidget.h \
		UpdateUserWidget.h \
		LibrarianWidget.h \
		InsertBookWidget.h \
		LibrarianController.h \
		ViewBookWidget.h \
		UserWidget.h \
		MyBookWidget.h \
		UserController.h \
		UserBookViewWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginWidget.o LoginWidget.cpp

Magazine.o: Magazine.cpp Magazine.h \
		Item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Magazine.o Magazine.cpp

main.o: main.cpp MainWindow.h \
		LoginWidget.h \
		LoginController.h \
		Data.h \
		Account.h \
		Item.h \
		AdminWidget.h \
		InsertUserWidget.h \
		AdminController.h \
		Controller.h \
		ViewUserWidget.h \
		UpdateUserWidget.h \
		LibrarianWidget.h \
		InsertBookWidget.h \
		LibrarianController.h \
		ViewBookWidget.h \
		UserWidget.h \
		MyBookWidget.h \
		UserController.h \
		UserBookViewWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		LoginWidget.h \
		LoginController.h \
		Data.h \
		Account.h \
		Item.h \
		AdminWidget.h \
		InsertUserWidget.h \
		AdminController.h \
		Controller.h \
		ViewUserWidget.h \
		UpdateUserWidget.h \
		LibrarianWidget.h \
		InsertBookWidget.h \
		LibrarianController.h \
		ViewBookWidget.h \
		UserWidget.h \
		MyBookWidget.h \
		UserController.h \
		UserBookViewWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

MyBookWidget.o: MyBookWidget.cpp MyBookWidget.h \
		UserController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyBookWidget.o MyBookWidget.cpp

UpdateUserWidget.o: UpdateUserWidget.cpp UpdateUserWidget.h \
		Controller.h \
		Account.h \
		AdminWidget.h \
		InsertUserWidget.h \
		AdminController.h \
		Data.h \
		Item.h \
		ViewUserWidget.h \
		LibrarianWidget.h \
		InsertBookWidget.h \
		LibrarianController.h \
		ViewBookWidget.h \
		UserWidget.h \
		MyBookWidget.h \
		UserController.h \
		UserBookViewWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UpdateUserWidget.o UpdateUserWidget.cpp

User.o: User.cpp User.h \
		Account.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

UserBookViewWidget.o: UserBookViewWidget.cpp UserBookViewWidget.h \
		UserController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		Book.h \
		Magazine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserBookViewWidget.o UserBookViewWidget.cpp

UserController.o: UserController.cpp UserController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserController.o UserController.cpp

UserWidget.o: UserWidget.cpp UserWidget.h \
		MyBookWidget.h \
		UserController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h \
		UserBookViewWidget.h \
		UpdateUserWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserWidget.o UserWidget.cpp

ViewBookWidget.o: ViewBookWidget.cpp ViewBookWidget.h \
		LibrarianController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ViewBookWidget.o ViewBookWidget.cpp

ViewUserWidget.o: ViewUserWidget.cpp ViewUserWidget.h \
		AdminController.h \
		Data.h \
		Account.h \
		Item.h \
		Controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ViewUserWidget.o ViewUserWidget.cpp

moc_AdminWidget.o: moc_AdminWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AdminWidget.o moc_AdminWidget.cpp

moc_InsertBookWidget.o: moc_InsertBookWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InsertBookWidget.o moc_InsertBookWidget.cpp

moc_InsertUserWidget.o: moc_InsertUserWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InsertUserWidget.o moc_InsertUserWidget.cpp

moc_LibrarianWidget.o: moc_LibrarianWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LibrarianWidget.o moc_LibrarianWidget.cpp

moc_LoginWidget.o: moc_LoginWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoginWidget.o moc_LoginWidget.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MyBookWidget.o: moc_MyBookWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyBookWidget.o moc_MyBookWidget.cpp

moc_UpdateUserWidget.o: moc_UpdateUserWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UpdateUserWidget.o moc_UpdateUserWidget.cpp

moc_UserBookViewWidget.o: moc_UserBookViewWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UserBookViewWidget.o moc_UserBookViewWidget.cpp

moc_UserWidget.o: moc_UserWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UserWidget.o moc_UserWidget.cpp

moc_ViewBookWidget.o: moc_ViewBookWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ViewBookWidget.o moc_ViewBookWidget.cpp

moc_ViewUserWidget.o: moc_ViewUserWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ViewUserWidget.o moc_ViewUserWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

